name: Frontend CD Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  REGISTRY: ${{ vars.REGISTRY }}
  REPO_NAME: ${{ vars.REPO_NAME }}
  IMAGE_TAG: ${{ vars.IMAGE_TAG }}
  BACKEND_URL: ${{ vars.BACKEND_URL }}

jobs:
  Lint_job:
    runs-on: ubuntu-latest
    environment: Devlopmnet Environment

    steps:
    - name: Checkout the Repository
      uses: actions/checkout@v4

    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: starter/frontend/package-lock.json

    - name: Install Dependencies
      working-directory: starter/frontend
      run: npm ci

    - name: Change Directory and run Lint
      run: cd starter/frontend && npm run lint

  Test_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the Repository
      uses: actions/checkout@v4

    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: starter/frontend/package-lock.json
        
    - name: Install Dependencies
      working-directory: starter/frontend
      run: npm ci
  
    - name: Test
      run: cd starter/frontend && npm run test



  Build:
    needs: [Lint_job, Test_job]
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the Repository
      uses: actions/checkout@v4
    
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: starter/frontend/package-lock.json

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{secrets.AWS_SESSION_TOKEN}}
        aws-region: us-east-1
  

    - name: Login to Amazon 
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2



    - name: Build, tag, and push docker image to Amazon ECR
      working-directory: starter/frontend
      run: |
        docker build --build-arg=REACT_APP_MOVIE_API_URL=$BACKEND_URL --tag $REGISTRY/$REPO_NAME:$IMAGE_TAG .
        docker push $REGISTRY/$REPO_NAME:$IMAGE_TAG

    - name: Configure Kubeconfig
      run:
       aws eks update-kubeconfig --name cluster --region us-east-1


    - name: Deploy Image in Amazon ECR to Amazon EKS
      working-directory: starter/frontend/k8s
      run: |
          kustomize edit set image frontend=$REGISTRY/$REPO_NAME:$IMAGE_TAG
          kustomize build | kubectl apply -f -
